plugins {
    id 'java'
    id 'maven-publish'
    id 'signing'
    id 'io.github.opendcs.maven.maven-central-upload'
}

def static versionLabel(gitInfo) {
    def branch = gitInfo.branchName // all branches are snapshots, only tags get released
    def tag = gitInfo.lastTag
    // tag is returned as is. Branch may need cleanup
    return branch == null ? tag : 99 + "." + branch.replace("/", "-") + "-SNAPSHOT"
}

def tmp_version = project.findProperty("versionOverride") ?: versionLabel(versionDetails())

group = 'org.opendcs.testing'
version = tmp_version


ext.shouldSign = (project.findProperty("sign") ?: "false") == "true"

if (shouldSign) {
    /*plugins.apply('dev.sigstore.sign')

    sigstoreSign {
        oidcClient {
            gitHub {
                audience.set("sigstore")
            }

            web {
                clientId.set("sigstore")
                issuer.set("https://oauth2.sigstore.dev/auth")
            }
        }
    }*/

    signing {
        def signingKey = project.getProperty("signingKey").trim().replace("\n","")
        def signingPassword = project.getProperty("signingKeyPassword")
        useInMemoryPgpKeys(signingKey, signingPassword)
}
}

publishing.publications.withType(MavenPublication) {
            pom {
                url = 'https://github.com/opendcs/gherkin-to-kiwi'

                scm {
                    connection = 'scm:git:https://github.com/opendcs/gherkin-to-kiwi.git'
                    developerConnection = 'scm:git:ssh://git@github.com:opendcs/gherkin-to-kiwi.git'
                    url = 'https://github.com/opendcs/gherkin-to-kiwi'
                }

                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }

                developers {
                    developer {
                        id = 'opendcs'
                        name = 'The OpenDCS Team'
                        email = 'https://github.com/opendcs'
                    }
                }
            }
        }

publishing {
    repositories {
        maven {
            name = "mavenCentralApi"
            url = "https://central.sonatype.com"
            def user = project.findProperty("centralApiUsername")
            def passwd = project.findProperty("centralApiPassword")
            credentials {
                username = user
                password = passwd
            }
        }
        mavenLocal()
    }
}
