buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies { 
            classpath "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:7.0.1.6134"
    }
}


plugins
{
    id 'eclipse'
    id "com.palantir.git-version" version "3.1.0"
    id 'org.sonarqube'
}

sonar {
    properties {
        property "sonar.projectKey", "opendcs_gherkin-to-kiwi"
        property "sonar.organization", "opendcs"
        property "sonar.host.url", "https://sonarcloud.io"
        property "sonar.pullrequest.provider", "GitHub"
        property "sonar.pullrequest.github.repository", "opendcs/gherkin-to-kiwi"
        property "sonar.projectVersion", sonarVersion()
    }
}

ext.sonarVersion = {
    def stdout = new ByteArrayOutputStream()
    exec {
        commandLine 'git', 'describe', '--tags', '--abbrev=0', "--always"
        standardOutput = stdout
    }
    return stdout.toString().trim() + "+"
}