plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:7.0.1.6134"
    implementation 'dev.sigstore:sigstore-gradle-sign-plugin:2.1.0'
    implementation 'io.github.opendcs.maven:maven-central-upload:0.1.2'
}