---
name: Release
on:
  workflow_call:
    inputs:
      branch:
       type: string
       required: true
    secrets:
      token:
       required: false
      signingKey:
        required: true
      signingKeyPassword:
        required: true
      ossrhUsername:
        required: true
      ossrhPassword:
        required: true
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        required: true
        description: Which Branch to make the build from
        options:
          - develop
      
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{inputs.branch}}
      - name: setup java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Set version
        run: echo "VERSION=${{inputs.branch}}" >> $GITHUB_ENV
      - name: show version
        run: echo ${VERSION}
      - name: Push to central
        run: |
          ./gradlew publish --info \
             -PversionOverride=$VERSION \
             -PsigningKeyPassword=${{ secrets.signingKeyPassword != null && secrets.signingKeyPassword || secrets.SIGNING_KEY_PASSWORD }} \
             -PossrhUsername=${{ secrets.ossrhUsername != null && secrets.ossrhUsername || secrets.OSSRH_USERNAME }} \
             -PossrhPassword=${{ secrets.ossrhPassword != null && secrets.ossrhPassword || secrets.OSSRH_PASSWORD }} \
             -PsigningKey=${{ secrets.signingKey != null && secrets.signingKey || secrets.SIGNING_KEY }}
